INSERT INTO candidates(name, phone_number, email, city, experience_years, faculty, recruitment_channel, birth_date)
VALUES ('Candidate1', '0712345678', 'candidate1@yahoo.com', 'Cluj', 2, 'Computer Science', 'Facebook', '1999-02-23');
INSERT INTO candidates(name, phone_number, email, city, experience_years, faculty, recruitment_channel, birth_date)
VALUES ('Candidate2', '0712345678', 'candidate2@yahoo.com', 'Cluj', 2, 'Computer Science', 'Facebook', '1999-02-23');
INSERT INTO candidates(name, phone_number, email, city, experience_years, faculty, recruitment_channel, birth_date)
VALUES ('Candidate3', '0712345678', 'candidate3@yahoo.com', 'Cluj', 2, 'Computer Science', 'Facebook', '1999-02-23');
INSERT INTO candidates(name, phone_number, email, city, experience_years, faculty, recruitment_channel, birth_date)
VALUES ('Candidate4', '0712345678', 'candidate4@yahoo.com', 'Cluj', 2, 'Computer Science', 'Facebook', '1999-02-23');
INSERT INTO candidates(name, phone_number, email, city, experience_years, faculty, recruitment_channel, birth_date)
VALUES ('Candidate5', '0712345678', 'candidate5@yahoo.com', 'Cluj', 2, 'Computer Science', 'Facebook', '1999-02-23');
INSERT INTO candidates(name, phone_number, email, city, experience_years, faculty, recruitment_channel, birth_date)
VALUES ('Candidate6', '0712345678', 'candidate6@yahoo.com', 'Cluj', 2, 'Computer Science', 'Facebook', '1999-02-23');