INSERT INTO users(email, password, role_id, full_name)
values ('test@yahoo.com', '123', 1, 'John Doe');
INSERT INTO users(email, password, role_id, full_name)
values ('anotherTest@yahoo.com', '1234', 2, 'Mark Doe');
INSERT INTO users(email, password, role_id, full_name)
values ('thirdTest@yahoo.com', '1234', 1, 'Jane Doe');
INSERT INTO users(email, password, role_id, full_name)
values ('fourthTest@yahoo.com', '1234', 2, 'Jane Roe');
INSERT INTO users(email, password, role_id, full_name)
values ('justintimberlake@yahoo.com', 'Password1!', 1, 'Justin Timberlake');
INSERT INTO users(email, password, role_id, full_name)
values ('marktwain@gmail.com', 'Password2!', 2, 'Mark Twain');
INSERT INTO users(email, password, role_id, full_name)
values ('janeaustin@yahoo.com', 'Password3!', 2, 'Jane Austin');
INSERT INTO users(email, password, role_id, full_name)
values ('kateroe@gmail.com', 'Password4!', 3, 'Kate Roe');
INSERT INTO users(email, password, role_id, full_name)
values ('bellahadid@gmail.com', 'Password5!', 4, 'Bella Hadid');
INSERT INTO users(email, password, role_id, full_name)
values ('katyperry@gmail.com', 'Password5!', 3, 'Katy Perry');
INSERT INTO users(email, password, role_id, full_name)
values ('jennifferaniston@gmail.com', 'Password5!', 4, 'Jennifer Aniston');